'use client';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Box, Divider } from '@chakra-ui/react';
import { SWRConfig } from 'swr';
import { AuthRedirect } from '@/components/shared/auth/AuthRedirect';
import { useState } from 'react';
import { LoadingScreen } from '@/components/shared/LoadingScreen/LoadingScreen';

const inter = Inter({ subsets: ['latin'] });
/*
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
*/
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [loggedIn, setLoggedIn] = useState(false);
  const onAuth = (login: boolean) => {
    if (login) setLoggedIn(true);
    else setLoggedIn(false);
  };
  return (
    <>
      <AuthRedirect loginFunc={onAuth} />
      {loggedIn ? children : <LoadingScreen />}
    </>
  );
}
